{% set python_min = "3.11" %}
{% set name = "sigfig" %}
{% set version = "1.3.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sigfig-{{ version }}.tar.gz
  sha256: a9e4fa37aa7595cc01b7207bfabf86cccd2d3edfddcdaa925ffd57dd77efcd9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - sortedcontainers >=2.4.0,<3.0.0

test:
  imports:
    - sigfig
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drakegroup/sigfig
  doc_url: https://sigfig.readthedocs.io/
  summary: Python library for rounding numbers (with expected results)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
