{% set python_min = '3.11' %}
{% set name = "sigfig" %}
{% set version = "1.3.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sigfig-{{ version }}.tar.gz
  sha256: 7c1e4cc10ae61f99a0bb0a96e0a5b1a4907570d5974016cb18d317f92ee36b5c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }},<4.0
    - sortedcontainers >=2.4.0,<3.0.0

test:
  imports:
    - sigfig
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drakegroup/sigfig
  doc_url: https://sigfig.readthedocs.io/
  summary: Python library for rounding numbers (with expected results)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
