{% set name = "sigfig" %}
{% set version = "1.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigfig-{{ version }}.tar.gz
  sha256: 86a067f8b977301ade0f5572405ea3b349d50fc6c2762f7ff2ab0f02f5515cfb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - sortedcontainers

test:
  imports:
    - sigfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drakegroup/sigfig
  doc_url: https://sigfig.readthedocs.io/
  summary: Python library for rounding numbers (with expected results)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
