{% set name = "sigfig" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigfig-{{ version }}.tar.gz
  sha256: 97a1225a38924e0586365500668fa3f2ba023bdb103207ea676507af378fce32

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - sortedcontainers

test:
  imports:
    - sigfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drakegroup/sigfig
  doc_url: https://sigfig.readthedocs.io/
  summary: Python library for rounding numbers (with expected results)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
