{% set name = "sigfig" %}
{% set version = "1.3.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigfig-{{ version }}.tar.gz
  sha256: 490fccae9ffcaa15377b215b1d8ddba0f33453053dd8d3a299bf0c5c954429a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.11,<4.0
    - sortedcontainers >=2.4.0,<3.0.0

test:
  imports:
    - sigfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drakegroup/sigfig
  doc_url: https://sigfig.readthedocs.io/
  summary: Python library for rounding numbers (with expected results)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
