{% set name = "sigfig" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sigfig-{{ version }}.tar.gz
  sha256: d6a720029c2fdb0f1413b14ba72f92db9ab95fe816d198fe7f6311d2bbdc5b61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.0
    - pip
  run:
    - python >=3.0
    - sortedcontainers

test:
  imports:
    - sigfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/drakegroup/sigfig
  doc_url: https://sigfig.readthedocs.io/
  summary: Python library for rounding numbers (with expected results)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
